version: "3.9"

services:
  database:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - '27017:27017'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: "backend"
    ports:
      - "4000:4000"
    volumes:
      - ./backend/:/app
    env_file:
      - ./backend/.env
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: "frontend"
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - database
      - backend
